name: Scarlett
favicon: null
layout_spectrum: 1
typography_spectrum: 0.11607
title: A Life on Screen
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#6793de'
    - '#bcc7e3'
    - '#2f0209'
    - '#9e1587'
  brandStrength: 0.875
  lightness: 0.375
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
